# CAFECA Default Config

title = "CAFECA"

[base]
folder = "CAFECA-framework"
static = "./build/"
debug = false

[blockchain]
type = "ethereum"

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",
  "get | /api/v1/chainId/:chainId/explorer/priceData/:tokenAddress | Bot.MockApis.getPriceData",
  "get | /api/v1/chainId/:chainId/explorer/tvlHistory | Bot.MockApis.getTvlHistory",
  "get | /api/v1/chainId/:chainId/explorer/volume24hr | Bot.MockApis.getVolume24hr",
  "get | /api/v1/chainId/:chainId/explorer/searchToken/:tokenAddress | Bot.Explorer.searchToken",
  "get | /api/v1/chainId/:chainId/explorer/tokenList | Bot.Explorer.getTokenList",
  "get | /api/v1/chainId/:chainId/explorer/poolList | Bot.MockApis.getPoolList",
  "post | /api/v1/chainId/:chainId/explorer/searchPool | Bot.MockApis.searchPool",
  "get | /api/v1/chainId/:chainId/explorer/poolDetail/:poolAddress | Bot.MockApis.getPoolDetail",
  "get | /api/v1/chainId/:chainId/explorer/addrTransHistory/:myAddress | Bot.MockApis.getAddrTransHistory",
  "get | /api/v1/chainId/:chainId/explorer/tokenDetail/:tokenAddress | Bot.MockApis.getTokenDetail",
]