# CAFECA Default Config

title = "CAFECA"

[base]
folder = "CAFECA-framework"
static = "./build/"
debug = false

[blockchain]
type = "ethereum"

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",
  "get | /api/v1/chainId/:chainId/explorer/candleStickData | Bot.Explorer.getCandleStickData",
  "get | /api/v1/chainId/:chainId/explorer/fixedDirectionData | Bot.Explorer.getFixedDirectionData",
  "get | /api/v1/chainId/:chainId/explorer/volume24hr | Bot.Explorer.getVolume24hr",
  "get | /api/v1/chainId/:chainId/explorer/searchToken/:tokenAddress | Bot.Explorer.searchToken",
  "get | /api/v1/chainId/:chainId/explorer/tokenList | Bot.Explorer.getTokenList",
]