# CAFECA Default Config

title = "CAFECA"

[base]
folder = "CAFECA-framework"
static = "./build/"
debug = false
apiKey = ""

[blockchain]
type = "ethereum"

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",
  "get | /api/v1/chainId/:chainId/explorer/priceData/:tokenAddress | Bot.Explorer.getTokenPriceData", # will remove after frontend change
  "get | /api/v1/chainId/:chainId/explorer/tokenPriceData/:tokenAddress | Bot.Explorer.getTokenPriceData",
  "get | /api/v1/chainId/:chainId/explorer/tvlHistory | Bot.Explorer.getTvlHistory",
  "get | /api/v1/chainId/:chainId/explorer/volume24hr | Bot.Explorer.getVolume24hr",
  "get | /api/v1/chainId/:chainId/explorer/searchToken/:tokenAddress | Bot.Explorer.searchToken",
  "get | /api/v1/chainId/:chainId/explorer/tokenList | Bot.Explorer.getTokenList",
  "get | /api/v1/chainId/:chainId/explorer/poolList | Bot.Explorer.getPoolList",
  "post | /api/v1/chainId/:chainId/explorer/searchPool | Bot.Explorer.searchPool",
  "get | /api/v1/chainId/:chainId/explorer/poolDetail/:poolContract | Bot.Explorer.getPoolDetail",
  "get | /api/v1/chainId/:chainId/explorer/addrTransHistory/:myAddress | Bot.Explorer.getAddrTransHistory",
  "get | /api/v1/chainId/:chainId/explorer/tokenDetail/:tokenAddress | Bot.Explorer.getTokenDetail",
  "get | /api/v1/chainId/:chainId/explorer/tokenHistory/:tokenAddress | Bot.Explorer.getTokenTransHistory",
  "get | /api/v1/chainId/:chainId/explorer/poolHistory/:poolContract | Bot.Explorer.getPoolTransHistory",
  "get | /api/v1/chainId/:chainId/explorer/overview | Bot.Explorer.getOverview",
  "get | /api/v1/chainId/:chainId/explorer/poolPriceData/:poolContract | Bot.Explorer.getPoolPriceData",
  "get | /api/v1/chainId/:chainId/explorer/poolPriceData/:poolContract/r | Bot.Explorer.getPoolPriceDataReciprocal",
  "get | /api/v1/chainId/:chainId/contract | Bot.Explorer.getContract",
  "get | /api/v1/chainId/:chainId/explorer/tokenTvlHistory/:tokenAddress | Bot.Explorer.getTokenTvlHistory",
  "get | /api/v1/chainId/:chainId/explorer/poolTvlHistory/:poolContract | Bot.Explorer.getPoolTvlHistory",
  "get | /api/v1/chainId/:chainId/explorer/poolFeeHistory/:poolContract | Bot.MockApis.getPoolFeeHistory",
  "get | /api/v1/chainId/:chainId/explorer/tokenVolume24hr/:tokenAddress | Bot.Explorer.getTokenVolume24hr",
  "get | /api/v1/chainId/:chainId/explorer/poolVolume24hr/:poolContract | Bot.Explorer.getPoolVolume24hr",

  "get | /api/v1/rate/crypto | Bot.Explorer.getCryptoRate",
  "get | /api/v1/rate/fiat | Bot.Explorer.getFiatRate",

  # temp
  "get | /api/v1/rate/crypto/chainId/:chainId | Bot.MockApis.getCryptoRate",
]