# CAFECA Default Config

title = "CAFECA"

[base]
folder = "CAFECA-framework"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]


[api]
pathname = [
  "get | / | Static.Views.index",
  "get | /manifest, /manifest.json | Static.Views.manifest",
  "get | /version | Static.Utils.readPackageInfo"
]