# CAFECA Default Config

title = "CAFECA"

[base]
folder = "CAFECA-framework"
static = "./build/"
debug = false

[blockchain]
type = "ethereum"

[database]


[api]
pathname = [
  "get | /version | Static.Utils.readPackageInfo",
  "get | /lacale, /lacale/:language | Static.Utils.getLocaleData",
  "get | /api/v1/chainId/:chainId/explorer/priceData/:tokenAddress | Bot.MockApis.getPriceData",
  "get | /api/v1/chainId/:chainId/explorer/tvlHistory | Bot.MockApis.getTvlHistory",
  "get | /api/v1/chainId/:chainId/explorer/volume24hr | Bot.MockApis.getVolume24hr",
  "get | /api/v1/chainId/:chainId/explorer/searchToken/:tokenAddress | Bot.Explorer.searchToken",
  "get | /api/v1/chainId/:chainId/explorer/tokenList | Bot.Explorer.getTokenList",
  "get | /api/v1/chainId/:chainId/explorer/poolList | Bot.Explorer.getPoolList",
  "post | /api/v1/chainId/:chainId/explorer/searchPool | Bot.Explorer.searchPool",
  "get | /api/v1/chainId/:chainId/explorer/poolDetail/:poolContract | Bot.MockApis.getPoolDetail",
  "get | /api/v1/chainId/:chainId/explorer/addrTransHistory/:myAddress | Bot.Explorer.getAddrTransHistory",
  "get | /api/v1/chainId/:chainId/explorer/tokenDetail/:tokenAddress | Bot.MockApis.getTokenDetail",
  "get | /api/v1/rate/crypto | Bot.Explorer.getCryptoRate",
  "get | /api/v1/rate/fiat | Bot.Explorer.getFiatRate",

  # temp
  "get | /api/v1/rate/crypto/chainId/:chainId | Bot.MockApis.getCryptoRate",
]