[TideWallet-Backend]
apiKey = "your apiKey Here"

# add your router detail set for each chain

# # router1
# [[TideBitSwapDatas]]
# router = ""               # address include 0x
# chainId = 3               # 1: eth mainnet, 3: ropsten
# factory = ""              # address include 0x, defined in router
# weth = ""                 # address include 0x, defined in router

# # router2
# [[TideBitSwapDatas]]
# router = ""               # address include 0x
# chainId = 3               # 1: eth mainnet, 3: ropsten
# factory = ""              # address include 0x, defined in router
# weth = ""                 # address include 0x, defined in router
